name: 'Publish to Release Repository'

on:
  release:
    types: [created] # Löst die Action nur aus, wenn ein neues Release erstellt wird

jobs:
  publish-release:
    runs-on: ubuntu-latest
    if: ${{ github.repository == 'webteam-leipzig/hio-typo3-connector' }} # Stellt sicher, dass die Action nur im Haupt-Repository ausgeführt wird
    steps:
      - name: 'Checkout Development Repo'
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: main

      - name: 'Checkout Release Repo'
        uses: actions/checkout@v4
        with:
          repository: 'wtl-public/hio-typo3-connector'
          token: ${{ secrets.RELEASE_REPO_TOKEN }}
          ref: main
          path: hio-release-repo
          fetch-depth: 0

      - name: 'Synchronize files'
        run: |
          cd hio-release-repo
          git status
          cd ..
          
          ls -lah hio-release-repo
          # Löscht alte Dateien im geklonten Release-Repo (außer .git-Verzeichnis)
          find hio-release-repo -mindepth 1 ! -name '.git' -exec rm -rf {} +
          ls -lah hio-release-repo

          cd hio-release-repo
          git status
          cd ..
          
          # Kopiert alle Dateien (außer .git) vom Entwicklungs- ins Release-Repo
          rsync -av --progress . hio-release-repo/ --exclude .git --exclude .github --exclude hio-release-repo

      - name: 'Configure Git and Push to Release Repo'
        env:
          RELEASE_REPO_TOKEN: ${{ secrets.RELEASE_REPO_TOKEN }}
        run: |
          git status
          git config --unset-all http.https://github.com/.extraheader
          # Wechsle in das Verzeichnis des Release-Repositories
          cd hio-release-repo
          git status                    
          # Konfiguriere Git mit dem Benutzer des Tokens (optional, aber gute Praxis)
          git config --global user.name "${{ github.actor }}"
          git config --global user.email "${{ github.actor }}@users.noreply.github.com"
          
          git add .
          git status
          
          # Commit nur, wenn es Änderungen gibt
          if ! git diff --staged --quiet; then
            git commit -m "chore: Sync from development release ${{ github.event.release.tag_name }}"
            git push --force https://token:${{ secrets.RELEASE_REPO_TOKEN }}@github.com/wtl-public/hio-typo3-connector.git main
          else
            echo "Keine Änderungen zum Committen."
          fi

      - name: 'Create Release in Release Repo'
        uses: softprops/action-gh-release@v2
        with:
          repository: 'wtl-public/hio-typo3-connector'
          token: ${{ secrets.RELEASE_REPO_TOKEN }}
          tag_name: ${{ github.ref_name }}
          name: ${{ github.event.release.name }}
          body: ${{ github.event.release.body }}
          prerelease: ${{ github.event.release.prerelease }}
          draft: false
